blank_issues_enabled: false
contact_links:
  - name: BUG Report | 缺陷报告
    url: https://github.com/linuxdeepin/dtk/issues/new?assignees=&labels=&template=bug-report.yml
    about: Please create bug reports to the issue board in our dtk repo.
  
  - name: docs-update | 文档补充
    url: https://github.com/linuxdeepin/dtk/issues/new?assignees=&labels=&template=docs-update.yml
    about: Please create docs-update to the issue board in our dtk repo.

  - name: unit-test-report | 单元测试报告
    url: https://github.com/linuxdeepin/dtk/issues/new?assignees=&labels=&template=unit-test-report.yml
    about: Please create unit-test-report to the issue board in our dtk repo.

  - name: Feature Request | 特性请求
    url: https://github.com/linuxdeepin/developer-center/discussions/new?category=features-request-ideas-%E7%89%B9%E6%80%A7%E8%AF%B7%E6%B1%82-%E5%A4%B4%E8%84%91%E9%A3%8E%E6%9A%B4
    about: Please create feature requests to the discussion board in our developer-center repo.
  - name: General Discussion & Questions | 常规讨论与问答
    url: https://github.com/linuxdeepin/developer-center/discussions/categories/q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97
    about: Please use the discussion board in our developer-center repo.
