Dtk--Widget--DScrollBar::add-line,Dtk--Widget--DScrollBar::sub-line,Dtk--Widget--DScrollBar::add-page,Dtk--Widget--DScrollBar::sub-page{
    background-color: transparent;
}

Dtk--Widget--DScrollBar{
    max-width: 10;
    margin-right: 1px;
    background-color: transparent;
}

Dtk--Widget--DScrollBar::handle{
    background-color: #33000000;
    border: 0.5px solid #11FFFFFF;
    border-radius: 3px;
}
