QLabel#ProductNameLabel {
    font-size:18px;
}

QLabel#VersionLabel {
    font-size:12px;
    color: #666666;
}

QLabel#WebsiteLabel {
    font-size:13px;
    color: #004EE5;
}

QLabel#AcknowledgementLabel {
    font-size:13px;
    color: #004EE5;
}

QLabel#DescriptionLabel {
    font-size:11px;
    font-weight: normal;
    color:#1A1A1A;
    border: none;
}

QLabel#LicenseLabel {
    font-size:11px;
    font-weight: normal;
    color:#1A1A1A;
    border: none;
}
