# TODO Maybe need to check if is apple or else 
file(GLOB MPRIS_HEADERS ${CMAKE_CURRENT_LIST_DIR}/private/mpris/*.h)
file(GLOB MPRIS_SOURCES ${CMAKE_CURRENT_LIST_DIR}/private/mpris/*.cpp)
file(GLOB WIDGETS_SOURCES ${CMAKE_CURRENT_LIST_DIR}/*.cpp ${CMAKE_CURRENT_LIST_DIR}/private/*.cpp)
file(GLOB WIDGETS_PRIVATE_HEADERS ${CMAKE_CURRENT_LIST_DIR}/private/*.h)
file(GLOB SETTINGS ${CMAKE_CURRENT_LIST_DIR}/private/settings/*)
file(GLOB NOTIFICATIONS ${CMAKE_CURRENT_LIST_DIR}/private/startupnotifications/*)
file(GLOB KEYBOARD ${CMAKE_CURRENT_LIST_DIR}/private/keyboardmonitor/*)
file(GLOB_RECURSE RESOURCES ${CMAKE_CURRENT_LIST_DIR}/*.qrc)
set(WIDGETS
  ${MPRIS_HEADERS}
  ${MPRIS_SOURCES}
  ${WIDGETS_SOURCES}
  ${WIDGETS_PRIVATE_HEADERS}
  ${SETTINGS}
  ${NOTIFICATIONS}
  ${KEYBOARD}
  ${RESOURCES}
)
