name: Call synchronize to dtk6
on:
  pull_request_target:
    paths-ignore:
      - "debian/**"
      - "archlinux/**"
      - "rpm/**"
      - ".obs/**"
      - ".github/**"

jobs:
  call-synchronize:
    uses: linuxdeepin/dtk/.github/workflows/synchronize-to-dtk6.yml@master
    secrets: inherit
    with:
      dest_repo: linuxdeepin/dtk6widget
      source_repo: ${{ github.event.pull_request.head.repo.full_name }}
      source_ref: ${{ github.event.pull_request.head.ref }}
      pull_number: ${{ github.event.pull_request.number }}
